lives = int(input("Please enter the number of lives "))
print()
energy = int(input("Please enter the energy level "))
print()
shield = int(input("Please enter shield level "))
print()
print("Lives:", "♥" * lives)
print("Energy:", "♦" * energy)
print("Shield:", "♦" * shield)
